#!/bin/sh

printf "\n"
printf " * Documentation:  https://github.com/sqrthree/motd.dynamic\n"
printf " * Management:     imsqrtthree@gmail.com\n"
printf " * Support:        imsqrtthree@gmail.com\n"
printf "\n"
